
version: '3.1'
services:
  mongo:
    image: mongo
  test:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/code
      - /code/src/node_modules
    depends_on:
      - mongo
    links:
      - mongo

